debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.min.board: debug
    org.springframework.web.servlet: debug    # request, response ???? ???.
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: kdm
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    open-in-view: false
  h2.console.enabled: true
  sql.init.mode: always

  thymeleaf3.decoupled-logic: true

  data.rest:
    base-path: /api
    detection-strategy: annotated

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always